### PR TITLE
CircleCI Running Until SEGFAULT

### PR DESCRIPTION
**Pull request by H0R5E**
Hi Kelley,

I got circle CI to run with the configuration in this PR on my account, but it crashes because you can only have 4GB of RAM on a free account. I noted that you had the resource_class key set to xlarge. Does that mean you have a paid account to test this out with?

Cheers,

Mat

### CODE REVIEW

**Comment by H0R5E** [comment]
Hmmm, 3098bf29325d14700520ae510a7a47995c8e70ef made no difference with 32GB of RAM, so I don't think that's the issue. I will keep investigating.

**Comment by H0R5E** [comment]
So, I've tried a more rudimentary approach to setting it up, but it's still crashing. Looking at the stack, it looks like it might be trying to show a dialogue before it dies (which it obviously can't do when running headless). I think everything is set so that it should not try to show anything, so I've opened a ticket with Mathworks support to see if they know what is going on. I'll let you know what they respond with.

**Comment by kmruehl** [comment]
@H0R5E I realized I hadn't responded to this thread even though we've discussed CircleCI in emails/calls. Based on [matlab-circleci-orb issue #25](https://github.com/mathworks/matlab-circleci-orb/issues/25) I think this issue has been resolved, and we should merge this PR. Can you remove "draft" from this PR so that it can be merged? Thanks!

https://app.circleci.com/jobs/github/H0R5E/WEC-Sim/16

**Comment by kmruehl** [comment]
Thank you @H0R5E!

**Pull request merged**
